catalog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),

    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),

    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^borrowedbooks/$', views.LoanedBooksStaffListView.as_view(), name='list-borrowed'),

    url(r'^book/(?P<pk>[-\w]+)/update/$', views.renew_book_librarian, name='renew-book-librarian'),

    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),

    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
import uuid
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=100,
                            help_text="Enter a book genre")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="covers")

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()])

    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])



class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m',
                              help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and (date.today() > self.due_back):
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f"({self.book.title}) - {self.id}"


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = "Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks = 4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .filters import BooksFilter
from .forms import RenewBookForm
from .models import Book, Author, BookInstance, Genre


@login_required
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Доступные книги (статус = 'a') available
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    num_books_with_word = Book.objects.filter(title__icontains="Вий").count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request, 'index.html',
        context={'num_books': num_books, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 'num_authors': num_authors,
                 "num_genres": num_genres, "num_books_with_word": num_books_with_word, 'num_visits': num_visits},
    )


class PageNumberPagination(object):
    pass


class BookListView(generic.ListView):
    # paginate_by = 10
    model = Book
    template_name = 'book_list.html'

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'title')
        return ordering

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = BooksFilter(self.request.GET, queryset=self.get_queryset())
        return context


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book
    template_name = 'book_detail.html'


class AuthorListView(generic.ListView):
    paginate_by = 10
    model = Author
    template_name = 'author_list.html'


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by(
            'due_back')


class LoanedBooksStaffListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_staff.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by(
            'due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse('list-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=2)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date, })

    return render(request, 'book_renew_librarian.html', {'form': form, 'bookinst': book_inst})


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    initial = {'date_of_death': '12/10/2016', }
    template_name = "author_form.html"


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    permission_required = 'catalog.can_mark_returned'
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    template_name = "author_form.html"


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = 'catalog.can_mark_returned'
    success_url = reverse_lazy('authors')
    template_name = "author_confirm_delete.html"


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    template_name = "book_form.html"


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    permission_required = 'catalog.can_mark_returned'
    fields = '__all__'
    template_name = "book_form.html"


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required = 'catalog.can_mark_returned'
    success_url = reverse_lazy('books')
    template_name = "book_confirm_delete.html"

catalog/templates/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{author.last_name}}</h1>

  {% if author.date_of_birth %}
  <p><strong>Years of life:</strong> <a href="">{{ author.date_of_birth }} - {{ author.date_of_death}}</a></p>
  {% endif %}

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books:</h4>
    {% for book in author.book_set.all %}
      <p><a href="{% url 'book-detail' book.pk %}">{{ book.title }} </a></p>
      <p>{{ book.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit"/>
</form>

{% endblock %}

catalog/templates/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}
        {% if author.date_of_birth %} {{author.date_of_birth}} - {{author.date_of_death}} {% endif %}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}

    {% include "paginate_generic.html" %}

{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        {% if user.is_authenticated %}
        <li><p>User: {{ user.get_username }}</p></li>
        <li><a href="{% url 'my-borrowed' %}">My borrowed</a></li>
        {% if perms.catalog.can_mark_returned %}
          <br>
          <li><p>Staff</p></li>
          <li><a href="{% url 'list-borrowed' %}">All borrowed</a></li>
          <li><a href="{% url 'author_create' %}">Add an Author</a></li>
          <li><a href="{% url 'book_create' %}">Add a book</a></li>
        {% endif %}
        <br>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
        <hr>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'books' %}">All books</a></li>
        <li><a href="{% url 'authors' %}">All authors</a></li>
      </ul>
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>

</div>
</body>
</html>

catalog/templates/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
  {% if book.image %}
  <img src="{{ book.image.url }}">
  {% endif %}
  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit"/>
</form>

{% endblock %}

catalog/templates/book_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% load widget_tweaks %}
{% block content %}
<h1>Book List</h1>

<!--<form method="GET">-->
<!--  {{ filter.form|bootstrap }}-->
<!--  <button type="submit" class="btn btn-primary">Search</button>-->
<!--</form>-->
<style>.well{
  max-width:76%;
  padding: 30px;
  margin:auto;
  margin-bottom: 30px;
}

</style>

<form method="get">
  <div class="well">
    <h4 style="margin-top: 0">Filter</h4>
    <div class="row">
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.title__icontains.label_tag }}
        {% render_field filter.form.title__icontains class="form-control" %}
      </div>
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.genre__name__icontains.label_tag }}
        {% render_field filter.form.genre__name__icontains class="form-control" %}
      </div>
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.isbn__icontains.label_tag }}
        {% render_field filter.form.isbn__icontains class="form-control" %}
      </div>
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.author.label_tag }}
        {% render_field filter.form.author class="form-control" %}
      </div>
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.language.label_tag }}
        {% render_field filter.form.language class="form-control" %}
      </div>
      <!--Ordering-->
      <div class="form-group col-sm-4 col-md-3">
        {{ filter.form.ordering.label_tag }}
        {% render_field filter.form.ordering class="form-control" %}
      </div>
    </div>
    <button type="submit" class="btn btn-primary">
      <span class="glyphicon glyphicon-search"></span> Search
    </button>
  </div>
</form>


{% if filter.qs %}
<div class="row">
  {% for book in filter.qs %}
  <div class="form-group col-sm-4 col-md-3">
    <div style="min-width: 300px;">
      {% if book.image %}
      <img src="{{ book.image.url }}" class="img-fluid" style="height:265px; width:173px;">
      <br>
      {% endif %}
      <div style="">
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        <br><br>
        <p>{{book.author}}</p>
      </div>
    </div>
  </div>
  {% endfor %}

</div>

{% else %}
<p>There are no books in the library.</p>
{% endif %}

{% include "paginate_generic.html" %}
{% endblock %}

catalog/templates/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}} - {{bookinst.borrower.first_name}} {{bookinst.borrower.last_name}}</p>
    <p {% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/bookinstance_list_borrowed_staff.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if perms.catalog.can_mark_returned %}

        {% if bookinstance_list %}
        <ul>
          {% for bookinst in bookinstance_list %}
          <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}} ({{ bookinst.due_back }})</a>
            {{bookinst.borrower.username}} - {{bookinst.borrower.first_name}} {{bookinst.borrower.last_name}}
            {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
          </li>
          {% endfor %}
        </ul>
        {% else %}
          <p>There are no books borrowed.</p>
        {% endif %}

    {% else %}
        <p>You don't have permission.</p>
    {% endif %}

{% endblock %}

catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Home page</title>{% endblock %}

{% block content %}
<h1>Local Library Home</h1>

<p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed.</p>

<div class="row">

  <div class="form-group col-sm-5 col-md-5">
    <img src="https://upload.wikimedia.org/wikipedia/commons/4/44/%D0%9A%D0%B8%D0%BD%D0%BE%D1%82%D0%B5%D0%B0%D1%82%D1%80_%22%D0%A0%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%22_%D0%B2_%D0%9D%D0%BE%D0%B2%D0%BE%D1%83%D1%80%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B5.JPG"
         alt="Library" style="width:100%;">

    <h2>Dynamic content</h2>

    <p>The library has the following record counts:</p>
    <ul>
      <li><strong>Books:</strong> {{ num_books }}</li>
      <li><strong>Copies:</strong> {{ num_instances }}</li>
      <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
      <li><strong>Authors:</strong> {{ num_authors }}</li>
      <li><strong>Genres:</strong> {{ num_genres }}</li>
      <li><strong>Books "Viy":</strong> {{ num_books_with_word }}</li>
    </ul>
    <br>
    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

  </div>

  <div class="form-group col-sm-6 col-md-6">
    <div class="row">
      <div class="form-group col-sm-6 col-md-6">
        <img src="https://thumbs.dreamstime.com/b/%D1%81%D0%B8%D0%BD%D0%B3%D0%B0%D0%BF%D1%83%D1%80-%D0%BE%D0%B5-%D0%B8%D1%8E%D0%BB%D1%8F-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B0-%D1%81%D0%B8%D0%BD%D0%B3%D0%B0%D0%BF%D1%83%D1%80%D0%B0-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D0%B8-150386902.jpg"
             class="img-fluid" style="width:94%;">
      </div>
      <div class="form-group col-sm-6 col-md-6">
        <img src="https://lh3.googleusercontent.com/proxy/28DWJbxtruChWQBFtQFhtZhnUuJ51zvOWTpL6RTSHEROpv2ZACWjR9nKzUADNbB4iqxx2Md4nZ520G5sI2cYtIiFEYFJDBxppWc1pDx3GvgNx17HmeWLmr0MGNGTlmP97vrW"
             class="img-fluid" style="width:94%;">
      </div>
      <div class="form-group col-sm-6 col-md-6">
        <img src="https://sntch.com/uploads/2019/04/phlBSMfloHuArwY8GfqT2g.jpg"
             class="img-fluid" style="width:94%;">
      </div>
      <div class="form-group col-sm-6 col-md-6">
        <img src="https://lh3.googleusercontent.com/proxy/VoA4-5IJ5lujuUhUmYLAs4y-z9Z9eWwltNbm793NdsIPZd00BLJh01tcjRpP2pnDHqq5eiU7wufHM-wYVmXxygZXq2H2sqJZ07jALF0yPjofrJ91eiCP9PtxwdQWfe_25CCo"
             class="img-fluid" style="width:94%;">
      </div>
    </div>
    <div style="margin-top: -20px;">
      <h2>About library</h2>

      <p>A library is a curated collection of sources of information and similar resources, selected by experts and made accessible to a defined community for reference or borrowing, often in a quiet environment conducive to study. It provides physical or digital access to material, and may be a physical location or a virtual space, or both. A library's collection can include books, periodicals, newspapers, manuscripts, films, maps, prints, documents, microform, CDs, cassettes, videotapes, DVDs, Blu-ray Discs, e-books, audiobooks, databases, and other formats. Libraries range widely in size up to millions of items. In Latin and Greek, the idea of a bookcase is represented by Bibliotheca and Bibliothēkē (Greek: βιβλιοθήκη): derivatives of these mean library in many modern languages, e.g. French bibliothèque.</p>
    </div>
  </div>

</div>


{% endblock %}

catalog/templates/paginate_generic.html
{% block paginate %}
  <div class="pagination">
         <span class="step-links">
             {% if page_obj.has_previous %}
                 <a href="?page=1">&laquo; first</a>
                 <a href="?page={{ page_obj.previous_page_number }}">previous</a>
             {% endif %}

             <span class="current">
                 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
             </span>

             {% if page_obj.has_next %}
                 <a href="?page={{ page_obj.next_page_number }}">next</a>
                 <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
             {% endif %}
         </span>
     </div>
{% endblock %}